### ISSUE TITLE
[FEATURE] Blog post for v0.13.0 

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/website#111]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

No

### Describe the solution that you would like.

Write a blog post to announce the v0.12.0 release, with the following content:

1. New features
2. Deprecations/removals
3. Installation instructions

**Comment by Adarsh-jaiss** [comment]
- Hey @qu1queee , i would love to write a blog post, if you could provide me a gist of changes and enhancement inluding some detailed info about the deprecation of alphav1 API group!

**Comment by qu1queee** [comment]
I'll ping you. Im currently working on this.

**Comment by Adarsh-jaiss** [comment]
> I'll ping you. Im currently working on this.

sure :)
