### ISSUE TITLE
typo on the docs page

### ISSUE THREAD

**Issue by majinghe** [shipwright-io/website#61]
On the page:  https://shipwright.io/docs/.  I think the content as blow has a type:
<img width="904" alt="Screen Shot 2021-11-16 at 11 13 10 PM" src="https://user-images.githubusercontent.com/42570491/142011720-951be123-d94b-4abc-a695-e9afb560e4b4.png">

On the docs says Shipwright’s Build API consists of **four** core CustomResourceDefinitions (CRDs), but the below content only contain three item, then i checked the crd on my kubernetes cluster
```
buildruns.shipwright.io                2021-11-16T14:10:52Z
builds.shipwright.io                   2021-11-16T14:10:52Z
buildstrategies.shipwright.io          2021-11-16T14:10:52Z
```

Only three exists, so i think this is a typo. Am i right, if yes, i will open an PR to fix this. If no, please add another crd. Thanks very much.

**Comment by qu1queee** [comment]
@majinghe apologies for such a late reply.  There are indeed 4 CRDS, the missing one is the `clusterbuildstrategies.shipwright.io` where the `scope` is cluster-wide, and not namespaced scope as in `buildstrategies.shipwright.io `. See this [example](https://github.com/shipwright-io/build/blob/main/samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml#L3) vs [this](https://github.com/shipwright-io/build/blob/main/samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml#L3).

**Comment by majinghe** [comment]
@qu1queee  Got it. Thanks for your info, i will close this issue.
