### ISSUE TITLE
Broken links to samples in buildtrategies.md

### ISSUE THREAD

**Issue by s-baier** [shipwright-io/website#69]
All Sample links in [buildstrategies](https://github.com/shipwright-io/website/blob/main/content/en/docs/api/buildstrategies.md) are broken.

The `samples` directory `https://github.com/shipwright-io/website/blob/main/content/en/docs/samples` which they are referring to, is completely missing.

Might be related to the mentioned sync problem with the `build` repo in #52 ?

**Comment by georgioupanayiotis** [comment]
@s-baier  can you please assign this to me?

**Comment by s-baier** [comment]
@georgioupanayiotis, unfortunately I'm not in the position to assign any issues.

**Comment by qu1queee** [comment]
@coreydaley any updates, per the refinement meeting discussions.

**Comment by qu1queee** [comment]
Closing in favour of https://github.com/shipwright-io/website/issues/74
