### ISSUE TITLE
Update existing docs and enhance the automation sync

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/website#74]
From grooming, what we want to achieve here is:

- [1] Ensure our existing docs in the website are up-to-date
- [2] Revisit our existing sync approach so that it can be easily triggered without intervention.

**Comment by SaschaSchwarze0** [comment]
From grooming: we will move the improvement of the sync approach into a separate issue. Goal for 0.10 is to have updated the documentation on the website, if needed manually synced.

**Comment by qu1queee** [comment]
Moving this to the community meeting for a broader discussion.
