### ISSUE TITLE
Update website to use AsciiDocs

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/website#75]
In the [community meeting on May 9th](https://github.com/shipwright-io/community/issues/84#issuecomment-1121106429), we discussed to potentially move from Markdown to AsciiDocs. Motivation can also be found in [slack](https://kubernetes.slack.com/archives/C019ZRGUEJC/p1652106394460249).

As we want to consume our documentation from repositories such as build on the website, we must ensure that we can host the website using AsciiDocs. This is therefore the first step.

**Comment by rolfedh** [comment]
Related:

- https://gohugo.io/content-management/formats/#list-of-content-formats
- https://asciidoctor.org/#asciidoctor-ecosystem

**Comment by coreydaley** [comment]
/close
it was decided that we would not use adoc
