### ISSUE TITLE
Code syntax highlighting doesn't work for asciidoc files. 

### ISSUE THREAD

**Issue by rolfedh** [shipwright-io/website#85]
Currently, when Hugo renders files like [content/en/docs/build/authentication.adoc](https://github.com/shipwright-io/website/pull/84/files#diff-3a59fe2accfcc9ef31eee079d7ff4a86b8ae3bb75ac528944bc9797368ff8937), code [syntax highlighting fails](https://deploy-preview-84--shipwright-io.netlify.app/docs/build/authentication/).

It looks like the solution might be to [install the rouge syntax highlighter](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/), which the Hugo docs [mention as an external helper extension](https://gohugo.io/content-management/formats/#external-helper-asciidoctor).

After rouge is installed, if we [uncomment the following lines in config.toml](https://github.com/shipwright-io/website/pull/84/files#r922322067), I believe syntax highlighting should work.  
```
  # [markup.asciidocExt]
  #   extensions = [asciidoctor-rouge]
```

**Comment by coreydaley** [comment]
/close
we will not be using adoc
