### ISSUE TITLE
Missing depenencies in "Getting Started" guide

### ISSUE THREAD

**Issue by rhuss** [shipwright-io/website#93]
* The getting started guide does not mention that Tekton is a pre-requisite when installing with vanilla K8s resource descriptors.
* The version is still pointing to 0.10.0

**Comment by qu1queee** [comment]
Hi @rhuss thanks for bringing this to our attention, we will fix it.

**Comment by qu1queee** [comment]
@ayushsatyam146 from the refinement meeting, any updates on this?

**Comment by ayushsatyam146** [comment]
@qu1queee I have raised PR #101 for solving this issue and I think @coreydaley has reviewed it as well.
